-- Table pour les configurations admin
create table if not exists public.admin_configs (
  id bigint generated by default as identity primary key,
  name text not null unique,
  excluded integer[] not null default '{}'::integer[],
  linked jsonb not null default '[]',
  admin_pass text not null default 's00r1',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_admin_configs_updated_at()
returns trigger as $$
begin
  new.updated_at := now();
  return new;
end;
$$ language plpgsql;

create trigger trg_admin_configs_updated_at
before update on public.admin_configs
for each row execute procedure public.set_admin_configs_updated_at();

alter table public.admin_configs enable row level security;

create policy anon_full_access on public.admin_configs
  for all to anon
  using (true)
  with check (true);
